alias vim='/c/Program\ Files\ \(x86\)/Vim/vim80/gvim.exe'
alias view='/c/Program\ Files\ \(x86\)/Vim/vim80/gvim.exe -R'
alias vimdiff='/c/Program\ Files\ \(x86\)/Vim/vim80/gvim.exe -d'
alias gvim='/c/Program\ Files\ \(x86\)/Vim/vim80/gvim.exe'
alias gvimdiff='/c/Program\ Files\ \(x86\)/Vim/vim80/gvim.exe -d'
